# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "426cf2079514ef3ada5cce14c477733f"
name = "app-tabs"
application_url = "https://usr-featured-ivory-towns.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "all-dev-theme.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://usr-featured-ivory-towns.trycloudflare.com/auth/callback",
  "https://usr-featured-ivory-towns.trycloudflare.com/auth/shopify/callback",
  "https://usr-featured-ivory-towns.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
